import type { ProposalSnapshot } from './types';

export function createPreviewSnapshot(): ProposalSnapshot {
  return {
    schemaVersion: 1,
    dealId: 'PREVIEW',
    version: 1,
    createdAt: new Date().toISOString(),
    deal: {
      dealname: 'عرض سعر منصة أجور',
      amount: '66000',
      deal_currency_code: 'SAR',
      legal_name_arabic: 'شركة نموذجية للتقنية',
      legal_name_english: 'Example Technology Company',
      billing_address: 'الرياض، المملكة العربية السعودية',
      cr_number: '1010123456',
      vat_number: '310123456700003',
    },
    company: {
      name: 'شركة نموذجية للتقنية',
      cr_number: '1010123456',
      vat_number: '310123456700003',
      billing_address: 'الرياض، المملكة العربية السعودية',
      city: 'الرياض',
      country: 'المملكة العربية السعودية',
      numberofemployees: '250',
      website: 'example.com',
    },
    contact: {
      firstname: 'محمد',
      lastname: 'أحمد',
      email: 'mohamed@example.com',
      phone: '+966 50 000 0000',
      jobtitle: 'مدير الموارد البشرية',
    },
    owner: {
      firstName: 'عبدالله',
      lastName: 'محمد',
      email: 'sales@ojoor.net',
    },
    lineItems: [
      {
        id: 'preview-1',
        name: 'الاشتراك السنوي في منصة أجور',
        description: 'إدارة الموارد البشرية والرواتب والخدمة الذاتية للموظفين.',
        quantity: '1',
        price: '60000',
        hs_pre_discount_amount: '60000',
        hs_total_discount: '5000',
        amount: '55000',
        hs_tax_amount: '8250',
        hs_line_item_currency_code: 'SAR',
        recurringbillingfrequency: 'annually',
        hs_sku: 'OJOOR-ANNUAL',
      },
      {
        id: 'preview-2',
        name: 'التهيئة والإطلاق',
        description: 'إعداد النظام، استيراد البيانات، التدريب، ودعم الإطلاق.',
        quantity: '1',
        price: '8000',
        hs_pre_discount_amount: '8000',
        amount: '8000',
        hs_tax_amount: '1200',
        hs_line_item_currency_code: 'SAR',
        hs_sku: 'OJOOR-IMPLEMENTATION',
      },
      {
        id: 'preview-3',
        name: 'إضافة الخدمة الذاتية للموظفين',
        description: 'وصول الموظفين إلى الطلبات والمستندات والبيانات الشخصية.',
        quantity: '250',
        price: '12',
        hs_pre_discount_amount: '3000',
        amount: '3000',
        hs_tax_amount: '450',
        hs_line_item_currency_code: 'SAR',
        recurringbillingfrequency: 'annually',
        hs_sku: 'OJOOR-ESS',
      },
    ],
    totals: {
      subtotal: 66000,
      discount: 5000,
      tax: 9900,
      grandTotal: 75900,
      currency: 'SAR',
    },
  };
}
